services:
# ---------------- API (Scalable Gateway) ----------------
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
     - .env  
    volumes:
      - ./uploads:/app/uploads # Shared disk space
    depends_on:
      redis:
        condition: service_healthy # Fixed typo
    restart: always    

# ---------------- Worker (Inference Engine) ----------------
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: 
      - .env
    volumes:
      - ./uploads:/app/uploads # Must match the API volume
    depends_on:
      redis:
        condition: service_healthy
      pushgateway:
        condition: service_started
    restart: always

# ---------------- Pushgateway (Worker Metrics) ----------------
  pushgateway:
    image: prom/pushgateway:v1.7.0
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: always

# ---------------- Redis (Main Database) ----------------
  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      # This ensures Redis is actually ready before API/Worker start
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
# ---------------- Redis Exporter (For Prometheus) ----------------
  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    restart: always

# ---------------- Prometheus (Monitoring) ----------------
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
      - worker
      - pushgateway
    restart: always

# ---------------- MLflow (Experiment Tracking) ----------------
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    container_name: mlflow
    # Command creates a persistent SQLite DB inside the volume
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000 
      --backend-store-uri sqlite:////mlflow/mlflow.db 
      --default-artifact-root /mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    restart: always

# ---------------- Grafana (Visualization) ----------------
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

# ---------------- Nginx (Load Balancer & Gateway) ----------------
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always

# ---------------- Persistent Volumes ----------------
volumes:
  redis_data:
  grafana_data:
  mlflow_data: